### ISSUE TITLE
Is it possible to only block apps for a specific amount of time?

### ISSUE THREAD

**Issue by ajkraus04** [NoodleOfDeath/react-native-screen-time-api#4]
Hey,

Is it possible only to block apps for a specific amount of time?

Best, 
Andrew

**Comment by ajkraus04** [comment]
One more thing, Is it possible to populate the dropdown with apps that are already blocked?

**Comment by NoodleOfDeath** [comment]
Hi andrew currently you will have to do this yourself by requesting authorization setting the family activity selection and then after a certain time in your react native app, you clear the activity selection

```typescript
import { ScreenTime } from 'react-native-screen-time-api';

React.useEffect(() => {
  ScreenTime.requestAuthorization('individual').then(async () => {
    const status = await ScreenTime.getAuthorizationStatus();
    console.log('Authorization status:', status); // 'approved', 'denied', or 'notDetermined'
    if (status !== 'approved') {
      throw new Error('user denied screen time access');
    }
    const selection = await ScreenTime.displayFamilyActivityPicker();
    console.log('Family activity selection:', selection);
    // selection will be `null` if user presses cancel
    if (selection) {
      await ScreenTime.setActivitySelection(selection); // sets the shields
      // disable after 5 hours
      setTimeout(() => ScreenTime.clearActivitySelection(), 60 * 60 * 5 * 1000);
    }
  });
}, []);
```

unfortunately, Apple doesn't even allow native code to call this screen time API in the background and requires the app to be in the foreground to deactivate Screen Time. Hopefully this will change with iOS 18 beta

**Comment by haider792** [comment]
is it possible to create a custom UI sheild? @NoodleOfDeath

**Comment by NoodleOfDeath** [comment]
yes, but that part has to be done natively because it has to be a shield configuration extension which requires a new target in Xcode https://developer.apple.com/documentation/managedsettingsui/shieldconfiguration

**Comment by lucasbara** [comment]
Hi! Is there any update on this? I want to create an app, where I can block for example Instagram for 30 minutes

**Comment by ajkraus04** [comment]
Yes, you can just schedule function to run to unblock all applications after x amount of time using his library.
