### ISSUE TITLE
iOS build failed: Some pods require a higher minimum deployment target.

### ISSUE THREAD

**Issue by stephengladney** [NoodleOfDeath/react-native-screen-time-api#7]
Trying to use the library in an Expo project. I know that the ScreenTime API is available in iOS 15.0+ so I'm using `expo-build-properties` to set version 15.0 as the deployment target.

```
"plugins": [
      "expo-router",
      [
        "expo-build-properties",
        {
          "ios": {
            "deploymentTarget": "15.0"
          }
        }
      ]
    ],
```

However, when trying to create a development build, I get the following error:

```
🍏 iOS build failed:
Some pods require a higher minimum deployment target.
You can use the expo-build-properties config plugin (https://docs.expo.dev/versions/latest/sdk/build-properties/) to override the default native build properties and set a different minimum deployment target.
```

**Comment by stephengladney** [comment]
Solution was to set minimum deployment target to 16.0

I'd recommend updating documentation to reflect this requirement

**Comment by NoodleOfDeath** [comment]
beat me to it! glad you solved this issue

**Comment by NoodleOfDeath** [comment]
@stephengladney if you want to make a PR to the readme you will be listed as a contributor. i will approve your changes
