### ISSUE TITLE
Error: Couldn’t communicate with a helper application.

### ISSUE THREAD

**Issue by stephengladney** [NoodleOfDeath/react-native-screen-time-api#8]
When trying to run `ScreenTime.requestAuthorization("individual")`, the following error is thrown:

```
[Error: Couldn’t communicate with a helper application.]
```

**Comment by NoodleOfDeath** [comment]
have you run `npx pod-install` and added the correct capabilities in Xcode?

**Comment by NoodleOfDeath** [comment]
Is this a separate issue or is this resolved?

**Comment by stephengladney** [comment]
I was hoping to avoid Xcode but I'll try that route. Looks like I need to upgrade Xcode. Will close this issue in the meantime
